title: Fea Alyana Garcia
description: Ruby on Rails developer
url: https://fajviray.github.io/jekyll-cv/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
